### ISSUE TITLE
Drawing Windows metafile generates an GDI exception

### ISSUE THREAD

**Issue by aconys** [vvvv/SVG#210]
Drawing in image works fine but in Metafile GDI generate an exception :
No problem in IE & Chrome the rendering is slow but fine

Exception :

System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.FillPath(Brush brush, GraphicsPath path)
   at Svg.SvgRenderer.FillPath(Brush brush, GraphicsPath path) in c:\Dev\Plot3D\SVG-master\Source\Rendering\SvgRenderer.cs:line 59
   at Svg.SvgVisualElement.RenderFill(ISvgRenderer renderer) in c:\Dev\Plot3D\SVG-master\Source\Basic Shapes\SvgVisualElement.cs:line 186
   at Svg.SvgVisualElement.Render(ISvgRenderer renderer, Boolean renderFilter) in c:\Dev\Plot3D\SVG-master\Source\Basic Shapes\SvgVisualElement.cs:line 152
   at Svg.SvgVisualElement.Render(ISvgRenderer renderer) in c:\Dev\Plot3D\SVG-master\Source\Basic Shapes\SvgVisualElement.cs:line 109
   at Svg.SvgElement.RenderChildren(ISvgRenderer renderer) in c:\Dev\Plot3D\SVG-master\Source\SvgElement.cs:line 726
   at Svg.SvgVisualElement.Render(ISvgRenderer renderer, Boolean renderFilter) in c:\Dev\Plot3D\SVG-master\Source\Basic Shapes\SvgVisualElement.cs:line 163
   at Svg.SvgVisualElement.Render(ISvgRenderer renderer) in c:\Dev\Plot3D\SVG-master\Source\Basic Shapes\SvgVisualElement.cs:line 109
   at Svg.SvgElement.RenderChildren(ISvgRenderer renderer) in c:\Dev\Plot3D\SVG-master\Source\SvgElement.cs:line 726
   at Svg.SvgElement.Render(ISvgRenderer renderer) in c:\Dev\Plot3D\SVG-master\Source\SvgElement.cs:line 714
   at Svg.SvgFragment.Render(ISvgRenderer renderer) in c:\Dev\Plot3D\SVG-master\Source\Document Structure\SvgFragment.cs:line 180
   at Svg.SvgDocument.Draw(Graphics graphics) in c:\Dev\Plot3D\SVG-master\Source\SvgDocument.cs:line 435
   at SVGViewer.SVGViewer.RenderSvg(SvgDocument svgDoc) in c:\Dev\Plot3D\SVG-master\Samples\SVGViewer\SvgViewer.cs:line 58
   at SVGViewer.SVGViewer.open_Click(Object sender, EventArgs e) in c:\Dev\Plot3D\SVG-master\Samples\SVGViewer\SvgViewer.cs:line 30

I changed the viewer source code for switch to metafile drawing.
In SvgViewer.cs replace RenderSvg function member by mine for support drawing Windows Metafile

       private void RenderSvg(SvgDocument svgDoc)
       {
			// GDI+
			Metafile metafile;
			using (var stream = new MemoryStream())
			using (Graphics ctrlGraphics = CreateGraphics())
			{
				IntPtr handle = ctrlGraphics.GetHdc();

				metafile = new Metafile(stream, handle);

				using (Graphics ig = Graphics.FromImage(metafile))
				{
					svgDoc.Draw(ig);
				}

				ctrlGraphics.ReleaseHdc(handle);
			}

			svgImage.Image = metafile;
        }
 

SVG file link (~22MB)

https://www.dropbox.com/s/73t53hkfpy6s9fn/03d56c43-162a-4776-97d8-ab85a48ef05f3DSceneSnapshot.svg?dl=0

**Comment by HeinrichAD** [comment]
Hello aconys

I think the problem here lies not in the SVG Rendering Engine, but in the GDI+ handling.

Note:
>"There is a theoretical limit of 65,536 GDI handles per session."
[more here](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724291(v=vs.85).aspx)

Try to create a rectangle for your metafile and see if an error occurres for the metafile creation or for the svg draw.

In my case this works with your example svg file:
```c#
// GDI+
Metafile metafile;
using (var stream = new MemoryStream())
using (Graphics ctrlGraphics = CreateGraphics())
{
    IntPtr handle = ctrlGraphics.GetHdc();

    var rect = new RectangleF(0, 0, 1000, 1000);
    metafile = new Metafile(stream, 
        handle,
        rect,
        MetafileFrameUnit.Pixel,
        EmfType.EmfPlusOnly);

    using (Graphics ig = Graphics.FromImage(metafile))
    {
        svgDoc.Width = rect.Width;
        svgDoc.Height = rect.Height;
        svgDoc.Draw(ig);
    }

    ctrlGraphics.ReleaseHdc(handle);
}

svgImage.Image = metafile;
svgImage.Image.Save(System.IO.Path.Combine(System.IO.Path.GetDirectoryName(svgDoc.BaseUri.LocalPath), "output.png"));
```

I hope this will help you.

**Comment by HeinrichAD** [comment]
To be more flexible you can also use flexible size values:

```CSharp
// GDI+
Metafile metafile;
using (var stream = new MemoryStream())
using (Graphics ctrlGraphics = CreateGraphics())
{
    IntPtr handle = ctrlGraphics.GetHdc();

    var rect = new RectangleF(0, 0, svgDoc.Width, svgDoc.Height);
    metafile = new Metafile(stream, 
        handle,
        rect,
        MetafileFrameUnit.Pixel,
        EmfType.EmfPlusOnly);

    using (Graphics ig = Graphics.FromImage(metafile))
    {
        svgDoc.Draw(ig);
    }

    ctrlGraphics.ReleaseHdc(handle);
}

svgImage.Image = metafile;
svgImage.Image.Save(System.IO.Path.Combine(System.IO.Path.GetDirectoryName(svgDoc.BaseUri.LocalPath), "output.png"));
```

**Comment by tebjan** [comment]
hope this is closed now with the mentioned pull request. otherwise please reopen it.
