### ISSUE TITLE
Exception: "message":"An error has occurred.","exceptionMessage": "ColorBlend object that was set is not valid.Position's last element must be equal to 1.0.  ColorBlend objects must be constructed with the same number of positions and color values.  Positions must be between 0.0 and 1.0, 1.0 indicating the last element in the array."

### ISSUE THREAD

**Issue by bromose** [vvvv/SVG#224]
Hi. I got:
The following exception:
{"message":"An error has occurred.","exceptionMessage":
"ColorBlend object that was set is not valid.Position's last element must be equal to 1.0. 
ColorBlend objects must be constructed with the same number of positions and color values. 
Positions must be between 0.0 and 1.0, 1.0 indicating the last element in the array."
,"exceptionType":"System.ArgumentException","stackTrace":" 
at System.Drawing.Drawing2D.LinearGradientBrush._SetInterpolationColors(ColorBlend blend)
at Svg.SvgLinearGradientServer.GetBrush(SvgVisualElement renderingElement, ISvgRenderer renderer, Single opacity, Boolean forStroke)
Svg.SvgVisualElement.RenderFill(ISvgRenderer renderer)
at Svg.SvgVisualElement.Render(ISvgRenderer renderer, Boolean renderFilter)
at Svg.SvgElement.RenderChildren(ISvgRenderer renderer)
at Svg.SvgVisualElement.Render(ISvgRenderer renderer, Boolean renderFilter)
at Svg.SvgElement.RenderChildren(ISvgRenderer renderer)

With help from :stackoverflow.com/questions/25268107/svg-renderer-throws-color-blend-object-not-valid-with-telerik-radhtmlchart

I was able to make a fix in "SvgGradientServer", protected ColorBlend GetColorBlend(ISvgRenderer renderer, float opacity, bool radial):

`                position =
                    radial
                        ? 1 -
                          (currentStop.Offset.ToDeviceValue(renderer, UnitRenderingType.Horizontal, this)/boundWidth)
                        : (currentStop.Offset.ToDeviceValue(renderer, UnitRenderingType.Horizontal, this)/boundWidth);

                **position = (float) Math.Round(position, 1, MidpointRounding.AwayFromZero);**`

Feel free to use my "hack" in your great projekt.

Best regards,
Kaj Bromose

**Comment by Steven0621** [comment]
the problem still exist! 
who knows how to solve?
thanks!

**Comment by bansan85** [comment]
I'm having this problem with the version 2.2.1 (the one available with nuget under visual studio express 2015 for Windows Desktop). No problem for Windows 32 bits. Fails sometimes on 64 bits computer.

I tried the master. It do not failed with this image anymore but still with some other.

I can confirm that adding
`position = (float) Math.Round(position, 1, MidpointRounding.AwayFromZero);`
after
`mergedOpacity = opacity * currentStop.Opacity;`
`position = ............`

solves the problem.

[DDFleche.zip](https://github.com/vvvv/SVG/files/469801/DDFleche.zip)
